#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Fedora install" --id BOOTID-fedora {
	insmod ext2
	insmod part_gpt
	search --set=root --label DISKLABEL
	set isofile="/linux.iso"
	loopback loop (${root})$isofile
	linux (loop)/images/pxeboot/vmlinuz inst.stage2=hd:/dev/PARTITION:$isofile inst.headless inst.vnc inst.vncpassword=xinstall
	#linux (loop)/images/pxeboot/vmlinuz inst.stage2=hd:/dev/PARTITION:$isofile inst.headless inst.sshd
	initrd (loop)/images/pxeboot/initrd.img
}
