#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Suse install" --id BOOTID-suse {
	insmod ext2
	insmod part_gpt
	search --set=root --label DISKLABEL
	set isofile="/linux.iso"
	loopback loop (${root})$isofile
	#linux (loop)/boot/x86_64/loader/linux ssh=1 sshpassword=xinstall
	linux (loop)/boot/x86_64/loader/linux vnc=1 vncpassword=xinstall
	initrd (loop)/boot/x86_64/loader/initrd
}
